// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillSnap_API.Data;

#nullable disable

namespace SkillSnap_API.Migrations
{
    [DbContext(typeof(SkillSnapDbContext))]
    [Migration("20251112032428_OneMoreForEfficiency")]
    partial class OneMoreForEfficiency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SkillSnap.Shared.Models.PortfolioUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PortfolioUsers");
                });

            modelBuilder.Entity("SkillSnap.Shared.Models.PortfolioUserSkill", b =>
                {
                    b.Property<int>("PortfolioUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortfolioUserId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Proficiency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("PortfolioUserId", "SkillId");

                    b.HasIndex("PortfolioUserId1");

                    b.HasIndex("SkillId");

                    b.HasIndex("SkillId1");

                    b.ToTable("PortfolioUserSkills");
                });

            modelBuilder.Entity("SkillSnap.Shared.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PortfolioUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioUserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SkillSnap.Shared.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("SkillSnap.Shared.Models.PortfolioUserSkill", b =>
                {
                    b.HasOne("SkillSnap.Shared.Models.PortfolioUser", null)
                        .WithMany("PortfolioUserSkills")
                        .HasForeignKey("PortfolioUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSnap.Shared.Models.PortfolioUser", "PortfolioUser")
                        .WithMany()
                        .HasForeignKey("PortfolioUserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSnap.Shared.Models.Skill", null)
                        .WithMany("SkillPortfolioUsers")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSnap.Shared.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioUser");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillSnap.Shared.Models.Project", b =>
                {
                    b.HasOne("SkillSnap.Shared.Models.PortfolioUser", null)
                        .WithMany("Projects")
                        .HasForeignKey("PortfolioUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSnap.Shared.Models.PortfolioUser", b =>
                {
                    b.Navigation("PortfolioUserSkills");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("SkillSnap.Shared.Models.Skill", b =>
                {
                    b.Navigation("SkillPortfolioUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
